---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-rbd-pvc
  namespace: honeybee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
